### ISSUE TITLE
Refine DividendableERC20

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/contracts#122]
Take the comments [here](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/557) and make sure we account for them.

**Comment by albertocuestacanada** [comment]
Also, if test coverage is high enough, get it out of drafts.

**Comment by uivlis** [comment]
From that link, all specifications are met, with this exception:
> * Contract owner can not collect dividends on minted tokens it holds.

Should we do this? It's like founding a company and then not be able to collect dividends because the company is yours.

**Comment by albertocuestacanada** [comment]
It seems that you are [not the only one](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/557#issuecomment-344726957) a bit puzzled by that constraint:

> Hi @frangio, sure thing. It really just means that newly minted tokens can’t dilute the dividend disbursement. The tokens have to be held by an account other than the contract to be counted toward determining the token holders share.

I don't see the point either or restricting dividends to the non-owner. I think it just introduces unnecessary complexity. Let's skip that one. Good job :+1:

**Comment by uivlis** [comment]
You shouldn't have close this issue, I'm not sure coverage is satisfactorily high enough.
