### ISSUE TITLE
Release Classifieds.sol

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/contracts#123]
- [ ] Rename Classifieds.sol as ClassifiedsAdvanced.sol.

- [ ] Rename ClassifiedsV2.sol as Classifieds.sol and get it out of drafts.

- [ ] Increase test coverage of the Classifieds.sol outside drafts until tests pass (90%?)

**Comment by albertocuestacanada** [comment]
We are still missing the README, could you please fix that?

**Comment by uivlis** [comment]
Sure! By the way, we are also missing the README.md for ERC20Dividenable, I'll do one for that, too.

**Comment by uivlis** [comment]
@albertocuestacanada Is this issue closable?

**Comment by albertocuestacanada** [comment]
The PR is closed, so yes.

There is some way to add the issue number in the PR (either at the end of the title or at the end of the description, not sure), and when the PR is merged the issue automatically closes. Let's find out how to do that.
