### ISSUE TITLE
write a welcome paragraph

### ISSUE THREAD

**Issue by obernardovieira** [HQ20/contracts#42]
Could you please write a paragraph to add to the README.md? Just as a welcome message, describing what contracts repository is.
something like this https://github.com/airbnb/streamalert
or https://github.com/kamranahmedse/developer-roadmap
or https://github.com/puppeteer/puppeteer
or maybe the top 3 here https://github.com/uber
I think you get the idea. Just one paragraph. The everything else is one me :+1:

**Comment by albertocuestacanada** [comment]
What about this?
**HQ20/contracts is an Ethereum project with contracts, libraries and examples to help you build fully-featured distributed applications for the real world.**

That seems to be in line with the examples that you provided:
 - StreamAlert is a serverless, realtime data analysis framework which empowers you to ingest, analyze, and alert on data from any environment, using datasources and alerting logic you define. 
 - Puppeteer is a Node library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol. Puppeteer runs headless by default, but can be configured to run full (non-headless) Chrome or Chromium.
  - Base is a design system comprised of modern, responsive, living components. Base Web is the React implementation of Base.

**Comment by albertocuestacanada** [comment]
https://github.com/HQ20/contracts/pull/49

**Comment by obernardovieira** [comment]
When I asked this, it was to be used at #17 
I said "I'll do the rest" :joy: 
anyway, I can merge that and work on top of it :+1:

**Comment by albertocuestacanada** [comment]
Awesome, thanks.
