### ISSUE TITLE
Bring coverage of UniswapExchange.sol up to 90%

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/contracts#50]
After bringing the contract to this repo, obviously.

**Comment by albertocuestacanada** [comment]
Right now high coverage is the requirement to get contracts out of drafts.

In a branch, get the exchange contracts out of drafts and increase coverage until the checks pass. I think that right now that is 95.83% :scream: 

On the upside, once getting there the branch can be merged and the contracts will be officially production.

**Comment by uivlis** [comment]
@albertocuestacanada Is this issue closable?

**Comment by albertocuestacanada** [comment]
Yes, let's link PRs to Issues, github can do this for us automagically.
