### ISSUE TITLE
Consider removing IssuanceToken from Issuance.sol

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/contracts#56]
Is there a reason we can't just use ERC20Detailed?

**Comment by uivlis** [comment]
Because I need ERC20Minted to mint the tokens to investors. And I also need ERC20Detailed, so that I can extract the decimals of the issuance token (used in the investing function, to check the investment for division by issuePrice).

**Comment by albertocuestacanada** [comment]
And why are you doing:
`_amount.div(10 ** uint256(issuanceToken.decimals())).mod(issuePrice) == 0,`

instead of `_amount.div(issuePrice)` (which is what you do in `withdraw`)?

**Comment by uivlis** [comment]
Initially, that's what I did. However, during tests, I noticed that the behaviour is not the one expected. For example, if issuanceToken has 18 decimals, and issuePrice is, say, 5, you would expect to receive 1 issuanceToken for 5 currencyTokens, but an error for 6 currencyTokens. Instead, with the original solution, you would have received 5.2 issuanceTokens, whereas fractional investments were not allowed. I'm not sure if I should keep this as it is, probably you'll want to revert it as it's in `withdraw`...

**Comment by albertocuestacanada** [comment]
Ah, but fractional investments are not allowed because we don't want to code in the contract the logic on what to do with payments that can't be translated into a single `currencyToken.mint()` call.

If the issuance token has decimals, there is no harm in minting fractions of an issuance token as long as you use exactly the currency wei that were transmitted.

So, if issuance token has 18 decimals, minting 5.2 issuance tokens is fine.

Imaging issuance token would have zero decimals and currency token has 18 decimals. That is what would happen if you would use an ether-like token for currency and a share-like token for issuance.

You would have to set the issue price in something like 50*10**18 (price in currency wei of the minimum fraction of an issuance token). You would want investors to send you multiples of 50*10**18, and `_amount.div(issuePrice)` would work just fine.

Long story to say that the behaviour you found above for 5.2 tokens issued is as expected and is correct. To test that fractions are not allowed you are looking for _fractions of issuance wei_.
