### ISSUE TITLE
Test with external project before releasing beta version

### ISSUE THREAD

**Issue by obernardovieira** [HQ20/contracts#69]
As we will be releasing the first beta version in two days, we must test it with an external project before doing it.

https://github.com/HQ20/contracts/milestone/2

Who can I assign it to?

**Comment by albertocuestacanada** [comment]
@obernardovieira, what does testing it with an external project mean?

**Comment by obernardovieira** [comment]
```
$ mkdir some-project
$ cd some-project
$ npm init -y
$ yarn add truffle
$ npx truffle init 
$ yarn add HQ20/contracts#dev
```
and write some contracts using the contracts from this repository.

**Comment by obernardovieira** [comment]
Is this tested?

**Comment by albertocuestacanada** [comment]
Should it have appeared here?
![image](https://user-images.githubusercontent.com/38806121/70811151-f209b100-1dbc-11ea-9c2d-3e0045efafe9.png)

**Comment by albertocuestacanada** [comment]
Trying with `npm install @hq20/contracts#dev` I get this:
![image](https://user-images.githubusercontent.com/38806121/70867852-1ce93600-1f72-11ea-9adf-cf15f77a45f1.png)

**Comment by obernardovieira** [comment]
see https://docs.npmjs.com/files/package.json#github-urls
so you should have used `yarn add HQ20/contracts#dev` instead.
I just tested this with a local repository.
Deployed ok, and also some methods calls are also ok
```bash
truffle(development)> mycontract = await MyContract.deployed()
undefined
truffle(development)> root = await mycontract.ROOT_ROLE()
undefined
truffle(development)> await mycontract.roleExists(root)
true
truffle(development)> web3.utils.toUtf8(root)
'ROOT'
truffle(development)> await mycontract.hasRole('0xe8a5e64E6EBb88F7DdCE7C91723e4d92b73B8FFc', root)
true
truffle(development)> await mycontract.hasRole('0xB1d9253c58E263242D8B8a790D486D20e64610DC', root)
false
truffle(development)> 
```

**Comment by obernardovieira** [comment]
https://www.npmjs.com/package/@hq20/contracts

**Comment by obernardovieira** [comment]
Close this issue when you see it :+1:

**Comment by albertocuestacanada** [comment]
I did use `yarn add HQ20/contracts#dev` first, but I was expecting the contracts to appear in `node_modules`: 
![image](https://user-images.githubusercontent.com/38806121/70912110-2a063380-200b-11ea-9970-8639b0b7b6a0.png)

**Comment by albertocuestacanada** [comment]
Ok, I see it now!
![image](https://user-images.githubusercontent.com/38806121/70912197-5d48c280-200b-11ea-975b-832b1da92045.png)
